[project]
name = "outlook-webhook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "msal>=1.32.3",
    "msgraph-core>=1.3.3",
    "msgraph-sdk>=1.31.0",
    "requests>=2.32.3",
]
